q1=input("adjective")
q2=input("verb")
q3=input("noun")
q4=input("noun")
q5=input("adverb")
print(f"The{q1} astronaut decided to")
print(f"to{q2} on mars suddenly")
print(f"a{q3}stole all of")
print(f"their {q4} and ran away very {q5}")
